In [5]:
import pandas as pd
import numpy as np
ser = pd.Series(np.random.randint(1,10,35))

### ý 1

In [ ]:
'''Ý nghĩa mã lệnh trên:
np.random.randint(1,10,35) trả về 1 mảng số nguyên ngẫu nhiên có giá trị min là 1, giá trị max là 10 với kích cỡ 35 phần tử
sau đó ta dùng pd.Series để tạo 1 chuỗi pandas từ mảng số ngẫu nhiên ở trên
'''

### ý 2

In [ ]:
arr = ser.values  # chuyển đối tượng series thành array
new_ser = arr.reshape((7,5))
print(new_ser, "\nđã định hình có 7 hàng 5 cột")

[[3 8 4 3 8]
 [5 3 4 9 2]
 [3 3 8 3 4]
 [8 9 9 1 8]
 [7 4 1 3 4]
 [8 2 7 7 8]
 [9 3 5 1 1]] 
đã định hình có 7 hàng 5 cột
